// Auto-generated by scripts/build-network.mjs from data/estacions.json and data/recorreguts.json
// Note: recorreguts.json contains bus route polylines. Metro/train lines not found in recorreguts.json
// are topologically ordered using nearest-neighbor + 2-opt open TSP path optimization.

import type { CompactNetwork } from '../import/compact-importer'

export const barcelonaCompact: CompactNetwork = {
  "id": "bcn-generated",
  "name": "Barcelona · Red real completa",
  "defaultTransfer": {
    "seconds": 180,
    "meters": 120,
    "accessibility": "partial"
  },
  "stations": [
    {
      "id": "aeroport-t1",
      "name": "Aeroport T1",
      "lat": 41.28829484,
      "lon": 2.07115199
    },
    {
      "id": "aeroport-t2",
      "name": "Aeroport T2",
      "lat": 41.30382333,
      "lon": 2.07311333
    },
    {
      "id": "alfons-x",
      "name": "Alfons X",
      "lat": 41.41241568,
      "lon": 2.16651196
    },
    {
      "id": "arc-de-triomf",
      "name": "Arc de Triomf",
      "lat": 41.39233666,
      "lon": 2.18116467
    },
    {
      "id": "artigues-sant-adria",
      "name": "Artigues | Sant Adrià",
      "lat": 41.43384823,
      "lon": 2.21777176
    },
    {
      "id": "av-carrilet",
      "name": "Av. Carrilet",
      "lat": 41.35852162,
      "lon": 2.10264529
    },
    {
      "id": "bac-de-roda",
      "name": "Bac de Roda",
      "lat": 41.41516206,
      "lon": 2.19550325
    },
    {
      "id": "badal",
      "name": "Badal",
      "lat": 41.37558063,
      "lon": 2.12740211
    },
    {
      "id": "badalona-pompeu-fabra",
      "name": "Badalona Pompeu Fabra",
      "lat": 41.4490526,
      "lon": 2.24409916
    },
    {
      "id": "barceloneta",
      "name": "Barceloneta",
      "lat": 41.38181098,
      "lon": 2.18478678
    },
    {
      "id": "baro-de-viver",
      "name": "Baró de Viver",
      "lat": 41.449936,
      "lon": 2.19956302
    },
    {
      "id": "bellvitge",
      "name": "Bellvitge",
      "lat": 41.35097352,
      "lon": 2.11091829
    },
    {
      "id": "besos",
      "name": "Besòs",
      "lat": 41.41983553,
      "lon": 2.2103013
    },
    {
      "id": "besos-mar",
      "name": "Besòs Mar",
      "lat": 41.415099,
      "lon": 2.21608159
    },
    {
      "id": "bogatell",
      "name": "Bogatell",
      "lat": 41.3951075,
      "lon": 2.1920124
    },
    {
      "id": "bon-pastor",
      "name": "Bon Pastor",
      "lat": 41.4361627,
      "lon": 2.20524027
    },
    {
      "id": "camp-de-l-arpa",
      "name": "Camp de l'Arpa",
      "lat": 41.41505961,
      "lon": 2.18149721
    },
    {
      "id": "can-boixeres",
      "name": "Can Boixeres",
      "lat": 41.36657075,
      "lon": 2.09150609
    },
    {
      "id": "can-cuias",
      "name": "Can Cuiàs",
      "lat": 41.4624131,
      "lon": 2.17305936
    },
    {
      "id": "can-peixauet",
      "name": "Can Peixauet",
      "lat": 41.44398591,
      "lon": 2.21002733
    },
    {
      "id": "can-serra",
      "name": "Can Serra",
      "lat": 41.36769339,
      "lon": 2.10275471
    },
    {
      "id": "can-tries-gornal",
      "name": "Can Tries | Gornal",
      "lat": 41.36089363,
      "lon": 2.11799258
    },
    {
      "id": "can-vidalet",
      "name": "Can Vidalet",
      "lat": 41.3712788,
      "lon": 2.09944503
    },
    {
      "id": "can-zam",
      "name": "Can Zam",
      "lat": 41.45666611,
      "lon": 2.19856942
    },
    {
      "id": "canyelles",
      "name": "Canyelles",
      "lat": 41.44175373,
      "lon": 2.16638755
    },
    {
      "id": "casa-de-l-aigua",
      "name": "Casa de l'Aigua",
      "lat": 41.45127784,
      "lon": 2.18483965
    },
    {
      "id": "catalunya",
      "name": "Catalunya",
      "lat": 41.38771322,
      "lon": 2.16971676
    },
    {
      "id": "centric",
      "name": "Cèntric",
      "lat": 41.32225002,
      "lon": 2.09346324
    },
    {
      "id": "ciutadella-vila-olimpica",
      "name": "Ciutadella | Vila Olímpica",
      "lat": 41.38664023,
      "lon": 2.19296314
    },
    {
      "id": "ciutat-de-la-justicia",
      "name": "Ciutat de la Justícia",
      "lat": 41.36313727,
      "lon": 2.13231497
    },
    {
      "id": "ciutat-meridiana",
      "name": "Ciutat Meridiana",
      "lat": 41.46080821,
      "lon": 2.17464988
    },
    {
      "id": "clot",
      "name": "Clot",
      "lat": 41.41051171,
      "lon": 2.18697812
    },
    {
      "id": "collblanc",
      "name": "Collblanc",
      "lat": 41.37583967,
      "lon": 2.11852563
    },
    {
      "id": "congres",
      "name": "Congrés",
      "lat": 41.42344043,
      "lon": 2.18118622
    },
    {
      "id": "cornella-centre",
      "name": "Cornellà Centre",
      "lat": 41.35728982,
      "lon": 2.07042809
    },
    {
      "id": "diagonal",
      "name": "Diagonal",
      "lat": 41.3956766,
      "lon": 2.16044376
    },
    {
      "id": "drassanes",
      "name": "Drassanes",
      "lat": 41.37653761,
      "lon": 2.17566417
    },
    {
      "id": "ecoparc",
      "name": "Ecoparc",
      "lat": 41.33015871,
      "lon": 2.13707118
    },
    {
      "id": "el-carmel",
      "name": "El Carmel",
      "lat": 41.42444977,
      "lon": 2.15509894
    },
    {
      "id": "el-coll-la-teixonera",
      "name": "El Coll | La Teixonera",
      "lat": 41.42199714,
      "lon": 2.1483485
    },
    {
      "id": "el-maresme-forum",
      "name": "El Maresme | Fòrum",
      "lat": 41.41168572,
      "lon": 2.21654808
    },
    {
      "id": "el-prat-estacio",
      "name": "El Prat Estació",
      "lat": 41.33199264,
      "lon": 2.0899271
    },
    {
      "id": "encants",
      "name": "Encants",
      "lat": 41.40723598,
      "lon": 2.18270037
    },
    {
      "id": "entenca",
      "name": "Entença",
      "lat": 41.38446686,
      "lon": 2.14561859
    },
    {
      "id": "ernest-lluch",
      "name": "Ernest Lluch",
      "lat": 41.37589761,
      "lon": 2.11202731
    },
    {
      "id": "esglesia-major",
      "name": "Església Major",
      "lat": 41.45479704,
      "lon": 2.21217687
    },
    {
      "id": "espanya",
      "name": "Espanya",
      "lat": 41.37545911,
      "lon": 2.149387
    },
    {
      "id": "europa-fira",
      "name": "Europa | Fira",
      "lat": 41.35756043,
      "lon": 2.12592378
    },
    {
      "id": "fabra-i-puig",
      "name": "Fabra i Puig",
      "lat": 41.4296326,
      "lon": 2.18366143
    },
    {
      "id": "fira",
      "name": "Fira",
      "lat": 41.35198805,
      "lon": 2.1304515
    },
    {
      "id": "florida",
      "name": "Florida",
      "lat": 41.36831605,
      "lon": 2.11002737
    },
    {
      "id": "foc",
      "name": "Foc",
      "lat": 41.35616087,
      "lon": 2.14180432
    },
    {
      "id": "fondo",
      "name": "Fondo",
      "lat": 41.45168719,
      "lon": 2.21853812
    },
    {
      "id": "foneria",
      "name": "Foneria",
      "lat": 41.36109924,
      "lon": 2.13822891
    },
    {
      "id": "fontana",
      "name": "Fontana",
      "lat": 41.40200888,
      "lon": 2.15302244
    },
    {
      "id": "gavarra",
      "name": "Gavarra",
      "lat": 41.35799493,
      "lon": 2.07927278
    },
    {
      "id": "girona",
      "name": "Girona",
      "lat": 41.39492035,
      "lon": 2.17082483
    },
    {
      "id": "glories",
      "name": "Glòries",
      "lat": 41.40227722,
      "lon": 2.18753747
    },
    {
      "id": "gorg",
      "name": "Gorg",
      "lat": 41.44025986,
      "lon": 2.23380706
    },
    {
      "id": "guinardo-hospital-de-sant-pau",
      "name": "Guinardó | Hospital de Sant Pau",
      "lat": 41.4159622,
      "lon": 2.17398904
    },
    {
      "id": "horta",
      "name": "Horta",
      "lat": 41.42969252,
      "lon": 2.1599744
    },
    {
      "id": "hospital-clinic",
      "name": "Hospital Clínic",
      "lat": 41.38860776,
      "lon": 2.15108107
    },
    {
      "id": "hospital-de-bellvitge",
      "name": "Hospital de Bellvitge",
      "lat": 41.34467745,
      "lon": 2.10724214
    },
    {
      "id": "hostafrancs",
      "name": "Hostafrancs",
      "lat": 41.37525363,
      "lon": 2.14329127
    },
    {
      "id": "jaume-i",
      "name": "Jaume I",
      "lat": 41.38412627,
      "lon": 2.17853146
    },
    {
      "id": "joanic",
      "name": "Joanic",
      "lat": 41.4064269,
      "lon": 2.16322503
    },
    {
      "id": "la-pau",
      "name": "La Pau",
      "lat": 41.42325112,
      "lon": 2.2058782
    },
    {
      "id": "la-sagrera",
      "name": "La Sagrera",
      "lat": 41.42069594,
      "lon": 2.18681133
    },
    {
      "id": "la-salut",
      "name": "La Salut",
      "lat": 41.4428171,
      "lon": 2.22473707
    },
    {
      "id": "les-corts",
      "name": "Les Corts",
      "lat": 41.38411968,
      "lon": 2.13087101
    },
    {
      "id": "les-moreres",
      "name": "Les Moreres",
      "lat": 41.32911864,
      "lon": 2.10307309
    },
    {
      "id": "lesseps",
      "name": "Lesseps",
      "lat": 41.40573803,
      "lon": 2.15040712
    },
    {
      "id": "liceu",
      "name": "Liceu",
      "lat": 41.38144543,
      "lon": 2.17303028
    },
    {
      "id": "llacuna",
      "name": "Llacuna",
      "lat": 41.39942504,
      "lon": 2.19771171
    },
    {
      "id": "llefia",
      "name": "Llefià",
      "lat": 41.44135958,
      "lon": 2.21690638
    },
    {
      "id": "llucmajor",
      "name": "Llucmajor",
      "lat": 41.43698465,
      "lon": 2.1733434
    },
    {
      "id": "maragall",
      "name": "Maragall",
      "lat": 41.42412908,
      "lon": 2.17741272
    },
    {
      "id": "maria-cristina",
      "name": "Maria Cristina",
      "lat": 41.38781569,
      "lon": 2.12579123
    },
    {
      "id": "marina",
      "name": "Marina",
      "lat": 41.39472529,
      "lon": 2.18580103
    },
    {
      "id": "mas-blau",
      "name": "Mas Blau",
      "lat": 41.31122536,
      "lon": 2.07347106
    },
    {
      "id": "mercabarna",
      "name": "Mercabarna",
      "lat": 41.33350192,
      "lon": 2.11125716
    },
    {
      "id": "mercat-nou",
      "name": "Mercat Nou",
      "lat": 41.3730027,
      "lon": 2.13353578
    },
    {
      "id": "montbau",
      "name": "Montbau",
      "lat": 41.43062016,
      "lon": 2.14503928
    },
    {
      "id": "monumental",
      "name": "Monumental",
      "lat": 41.40052374,
      "lon": 2.17946167
    },
    {
      "id": "mundet",
      "name": "Mundet",
      "lat": 41.43564527,
      "lon": 2.1484718
    },
    {
      "id": "navas",
      "name": "Navas",
      "lat": 41.41618671,
      "lon": 2.18705678
    },
    {
      "id": "onze-de-setembre",
      "name": "Onze de Setembre",
      "lat": 41.42961749,
      "lon": 2.19361021
    },
    {
      "id": "palau-reial",
      "name": "Palau Reial",
      "lat": 41.38598006,
      "lon": 2.11853818
    },
    {
      "id": "paral-lel",
      "name": "Paral·lel",
      "lat": 41.37458126,
      "lon": 2.16902937
    },
    {
      "id": "parc-de-montjuic",
      "name": "Parc de Montjuïc",
      "lat": 41.36895607,
      "lon": 2.16326877
    },
    {
      "id": "parc-logistic",
      "name": "Parc Logístic",
      "lat": 41.34166355,
      "lon": 2.12740125
    },
    {
      "id": "parc-nou",
      "name": "Parc Nou",
      "lat": 41.31662845,
      "lon": 2.08792943
    },
    {
      "id": "passeig-de-gracia",
      "name": "Passeig de Gràcia",
      "lat": 41.39010632,
      "lon": 2.16735101
    },
    {
      "id": "penitents",
      "name": "Penitents",
      "lat": 41.41827912,
      "lon": 2.14097179
    },
    {
      "id": "pep-ventura",
      "name": "Pep Ventura",
      "lat": 41.44390457,
      "lon": 2.23795938
    },
    {
      "id": "placa-de-sants",
      "name": "Plaça de Sants",
      "lat": 41.37553225,
      "lon": 2.13557556
    },
    {
      "id": "placa-del-centre",
      "name": "Plaça del Centre",
      "lat": 41.38192171,
      "lon": 2.13588371
    },
    {
      "id": "poble-sec",
      "name": "Poble Sec",
      "lat": 41.3749962,
      "lon": 2.16024482
    },
    {
      "id": "poblenou",
      "name": "Poblenou",
      "lat": 41.40371612,
      "lon": 2.20337123
    },
    {
      "id": "port-comercial-la-factoria",
      "name": "Port Comercial | La Factoria",
      "lat": 41.33598305,
      "lon": 2.14065723
    },
    {
      "id": "provencana",
      "name": "Provençana",
      "lat": 41.36135378,
      "lon": 2.12409979
    },
    {
      "id": "pubilla-cases",
      "name": "Pubilla Cases",
      "lat": 41.37383759,
      "lon": 2.10720906
    },
    {
      "id": "rambla-just-oliveras",
      "name": "Rambla Just Oliveras",
      "lat": 41.36408991,
      "lon": 2.09974934
    },
    {
      "id": "rocafort",
      "name": "Rocafort",
      "lat": 41.37923215,
      "lon": 2.15456248
    },
    {
      "id": "roquetes",
      "name": "Roquetes",
      "lat": 41.44766968,
      "lon": 2.17609769
    },
    {
      "id": "sagrada-familia",
      "name": "Sagrada Família",
      "lat": 41.40441909,
      "lon": 2.17449041
    },
    {
      "id": "sant-andreu",
      "name": "Sant Andreu",
      "lat": 41.43661037,
      "lon": 2.1911884
    },
    {
      "id": "sant-antoni",
      "name": "Sant Antoni",
      "lat": 41.37983284,
      "lon": 2.16324114
    },
    {
      "id": "sant-ildefons",
      "name": "Sant Ildefons",
      "lat": 41.36338108,
      "lon": 2.08439279
    },
    {
      "id": "sant-marti",
      "name": "Sant Martí",
      "lat": 41.41906362,
      "lon": 2.20072391
    },
    {
      "id": "sant-pau-dos-de-maig",
      "name": "Sant Pau | Dos de Maig",
      "lat": 41.41075328,
      "lon": 2.17601603
    },
    {
      "id": "sant-roc",
      "name": "Sant Roc",
      "lat": 41.43583082,
      "lon": 2.22860618
    },
    {
      "id": "santa-coloma",
      "name": "Santa Coloma",
      "lat": 41.45106735,
      "lon": 2.20796946
    },
    {
      "id": "santa-eulalia",
      "name": "Santa Eulàlia",
      "lat": 41.36881637,
      "lon": 2.12861726
    },
    {
      "id": "santa-rosa",
      "name": "Santa Rosa",
      "lat": 41.44685031,
      "lon": 2.21580898
    },
    {
      "id": "sants-estacio",
      "name": "Sants Estació",
      "lat": 41.38096118,
      "lon": 2.14189238
    },
    {
      "id": "selva-de-mar",
      "name": "Selva de Mar",
      "lat": 41.40800151,
      "lon": 2.2091225
    },
    {
      "id": "singuerlin",
      "name": "Singuerlín",
      "lat": 41.45941352,
      "lon": 2.20542885
    },
    {
      "id": "tarragona",
      "name": "Tarragona",
      "lat": 41.378493,
      "lon": 2.14533577
    },
    {
      "id": "teleferic-parc-de-montjuic",
      "name": "Telefèric Parc de Montjuïc",
      "lat": 41.36895607,
      "lon": 2.16326877
    },
    {
      "id": "tetuan",
      "name": "Tetuan",
      "lat": 41.39488745,
      "lon": 2.17555918
    },
    {
      "id": "torras-i-bages",
      "name": "Torras i Bages",
      "lat": 41.44322471,
      "lon": 2.19067063
    },
    {
      "id": "torrassa",
      "name": "Torrassa",
      "lat": 41.36826071,
      "lon": 2.11608943
    },
    {
      "id": "torre-baro-vallbona",
      "name": "Torre Baró | Vallbona",
      "lat": 41.45919575,
      "lon": 2.17988358
    },
    {
      "id": "trinitat-nova",
      "name": "Trinitat Nova",
      "lat": 41.44976211,
      "lon": 2.18285521
    },
    {
      "id": "trinitat-vella",
      "name": "Trinitat Vella",
      "lat": 41.44895649,
      "lon": 2.19383728
    },
    {
      "id": "universitat",
      "name": "Universitat",
      "lat": 41.3855879,
      "lon": 2.16405855
    },
    {
      "id": "urgell",
      "name": "Urgell",
      "lat": 41.3824874,
      "lon": 2.15889091
    },
    {
      "id": "urquinaona",
      "name": "Urquinaona",
      "lat": 41.38884688,
      "lon": 2.17366776
    },
    {
      "id": "vall-d-hebron",
      "name": "Vall d'Hebron",
      "lat": 41.42512314,
      "lon": 2.14251471
    },
    {
      "id": "vallcarca",
      "name": "Vallcarca",
      "lat": 41.41197495,
      "lon": 2.14433731
    },
    {
      "id": "valldaura",
      "name": "Valldaura",
      "lat": 41.43799608,
      "lon": 2.15687783
    },
    {
      "id": "verdaguer",
      "name": "Verdaguer",
      "lat": 41.39996848,
      "lon": 2.16831288
    },
    {
      "id": "verneda",
      "name": "Verneda",
      "lat": 41.43000446,
      "lon": 2.20988342
    },
    {
      "id": "via-julia",
      "name": "Via Júlia",
      "lat": 41.44373023,
      "lon": 2.17854996
    },
    {
      "id": "vilapicina",
      "name": "Vilapicina",
      "lat": 41.43046507,
      "lon": 2.16761908
    },
    {
      "id": "virrei-amat",
      "name": "Virrei Amat",
      "lat": 41.42970334,
      "lon": 2.17491306
    },
    {
      "id": "zal-riu-vell",
      "name": "ZAL | Riu Vell",
      "lat": 41.32370587,
      "lon": 2.13309543
    },
    {
      "id": "zona-franca",
      "name": "Zona Franca",
      "lat": 41.3429761,
      "lon": 2.14496443
    },
    {
      "id": "zona-universitaria",
      "name": "Zona Universitària",
      "lat": 41.38400257,
      "lon": 2.11138892
    }
  ],
  "lines": [
    {
      "id": "FM",
      "code": "FM",
      "name": "Funicular de Montjuïc",
      "mode": "funicular",
      "color": "#5FA33A",
      "depthMeters": -20,
      "cruiseSpeedMps": 2.5,
      "stations": [
        "parc-de-montjuic",
        "paral-lel"
      ]
    },
    {
      "id": "L1",
      "code": "L1",
      "name": "Hospital de Bellvitge – Fondo",
      "mode": "metro",
      "color": "#E2231A",
      "depthMeters": -14,
      "cruiseSpeedMps": 9.5,
      "stations": [
        "hospital-de-bellvitge",
        "bellvitge",
        "av-carrilet",
        "rambla-just-oliveras",
        "can-serra",
        "florida",
        "torrassa",
        "santa-eulalia",
        "mercat-nou",
        "placa-de-sants",
        "hostafrancs",
        "espanya",
        "rocafort",
        "urgell",
        "universitat",
        "catalunya",
        "urquinaona",
        "arc-de-triomf",
        "marina",
        "glories",
        "clot",
        "navas",
        "la-sagrera",
        "fabra-i-puig",
        "sant-andreu",
        "torras-i-bages",
        "trinitat-vella",
        "baro-de-viver",
        "santa-coloma",
        "fondo"
      ]
    },
    {
      "id": "L2",
      "code": "L2",
      "name": "Paral·lel – Badalona Pompeu Fabra",
      "mode": "metro",
      "color": "#9B2B8E",
      "depthMeters": -26,
      "cruiseSpeedMps": 9.5,
      "stations": [
        "paral-lel",
        "sant-antoni",
        "universitat",
        "passeig-de-gracia",
        "tetuan",
        "monumental",
        "sagrada-familia",
        "encants",
        "clot",
        "bac-de-roda",
        "sant-marti",
        "la-pau",
        "verneda",
        "artigues-sant-adria",
        "sant-roc",
        "gorg",
        "pep-ventura",
        "badalona-pompeu-fabra"
      ]
    },
    {
      "id": "L3",
      "code": "L3",
      "name": "Zona Universitària – Trinitat Nova",
      "mode": "metro",
      "color": "#2E9E48",
      "depthMeters": -18,
      "cruiseSpeedMps": 9.5,
      "stations": [
        "zona-universitaria",
        "palau-reial",
        "maria-cristina",
        "les-corts",
        "placa-del-centre",
        "sants-estacio",
        "tarragona",
        "espanya",
        "poble-sec",
        "paral-lel",
        "drassanes",
        "liceu",
        "catalunya",
        "passeig-de-gracia",
        "diagonal",
        "fontana",
        "lesseps",
        "vallcarca",
        "penitents",
        "vall-d-hebron",
        "montbau",
        "mundet",
        "valldaura",
        "canyelles",
        "roquetes",
        "trinitat-nova"
      ]
    },
    {
      "id": "L4",
      "code": "L4",
      "name": "Trinitat Nova – La Pau",
      "mode": "metro",
      "color": "#F2B705",
      "depthMeters": -22,
      "cruiseSpeedMps": 9.5,
      "stations": [
        "trinitat-nova",
        "via-julia",
        "llucmajor",
        "maragall",
        "guinardo-hospital-de-sant-pau",
        "alfons-x",
        "joanic",
        "verdaguer",
        "girona",
        "passeig-de-gracia",
        "urquinaona",
        "jaume-i",
        "barceloneta",
        "ciutadella-vila-olimpica",
        "bogatell",
        "llacuna",
        "poblenou",
        "selva-de-mar",
        "el-maresme-forum",
        "besos-mar",
        "besos",
        "la-pau"
      ]
    },
    {
      "id": "L5",
      "code": "L5",
      "name": "Cornellà Centre – Vall d’Hebron",
      "mode": "metro",
      "color": "#0072BC",
      "depthMeters": -32,
      "cruiseSpeedMps": 9.5,
      "stations": [
        "cornella-centre",
        "gavarra",
        "sant-ildefons",
        "can-boixeres",
        "can-vidalet",
        "pubilla-cases",
        "ernest-lluch",
        "collblanc",
        "badal",
        "placa-de-sants",
        "sants-estacio",
        "entenca",
        "hospital-clinic",
        "diagonal",
        "verdaguer",
        "sagrada-familia",
        "sant-pau-dos-de-maig",
        "camp-de-l-arpa",
        "la-sagrera",
        "congres",
        "maragall",
        "virrei-amat",
        "vilapicina",
        "horta",
        "el-carmel",
        "el-coll-la-teixonera",
        "vall-d-hebron"
      ]
    },
    {
      "id": "L9N",
      "code": "L9N",
      "name": "La Sagrera – Can Zam",
      "mode": "metro",
      "color": "#E65100",
      "depthMeters": -40,
      "cruiseSpeedMps": 10,
      "stations": [
        "la-sagrera",
        "onze-de-setembre",
        "bon-pastor",
        "can-peixauet",
        "santa-rosa",
        "fondo",
        "esglesia-major",
        "singuerlin",
        "can-zam"
      ]
    },
    {
      "id": "L9S",
      "code": "L9S",
      "name": "Aeroport T1 – Zona Universitària",
      "mode": "metro",
      "color": "#E65100",
      "depthMeters": -40,
      "cruiseSpeedMps": 10,
      "stations": [
        "zona-universitaria",
        "collblanc",
        "torrassa",
        "can-tries-gornal",
        "europa-fira",
        "fira",
        "parc-logistic",
        "mercabarna",
        "les-moreres",
        "el-prat-estacio",
        "centric",
        "parc-nou",
        "mas-blau",
        "aeroport-t2",
        "aeroport-t1"
      ]
    },
    {
      "id": "L10N",
      "code": "L10N",
      "name": "La Sagrera – Gorg",
      "mode": "metro",
      "color": "#00A099",
      "depthMeters": -40,
      "cruiseSpeedMps": 10,
      "stations": [
        "gorg",
        "la-salut",
        "llefia",
        "bon-pastor",
        "onze-de-setembre",
        "la-sagrera"
      ]
    },
    {
      "id": "L10S",
      "code": "L10S",
      "name": "ZAL | Riu Vell – Collblanc",
      "mode": "metro",
      "color": "#00A099",
      "depthMeters": -40,
      "cruiseSpeedMps": 10,
      "stations": [
        "collblanc",
        "torrassa",
        "can-tries-gornal",
        "provencana",
        "ciutat-de-la-justicia",
        "foneria",
        "foc",
        "zona-franca",
        "port-comercial-la-factoria",
        "ecoparc",
        "zal-riu-vell"
      ]
    },
    {
      "id": "L11",
      "code": "L11",
      "name": "Trinitat Nova – Can Cuiàs",
      "mode": "metro",
      "color": "#B2D235",
      "depthMeters": -15,
      "cruiseSpeedMps": 8,
      "stations": [
        "can-cuias",
        "ciutat-meridiana",
        "torre-baro-vallbona",
        "casa-de-l-aigua",
        "trinitat-nova"
      ]
    }
  ],
  "transfers": []
}
